apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app:  { .Values.namespace.app }
  name: { .Values.namespace.app }
  namespace: { .Values.namespace.name }
spec:
  ports:
  - name: { .Values.service.port }-{ .Values.service.targetPort }
    port: { .Values.service.port }
    protocol:  { .Values.service.protocol }
    targetPort: { .Values.service.targetPort }
  selector:
    app:  { .Values.namespace.app }
  type: { .Values.service.type }
status:
  loadBalancer: {}